// sin_tables.cpp - generates the sine tables the engine + MROTATE rely on.
//
// The original demo generated these at build time; the archived INC\SIN file
// is a dword sine approximation and `sinus.inc` was never archived. Both are
// 1024-entry, 2^15-scaled true sines here. The engine reads `sinus` as words,
// MROTATE/VIRTUAL read `sin` as dwords.
//
// Output: sin_tables.asm
//   sin    : 1024 x dd, round(sin(2*pi*i/1024)*32767)
//   sinus  : 1024 x dw, identical values

#include <cmath>
#include <cstdio>
#include <cstdint>

static int sv(int i) {
    double a = (2.0 * 3.14159265358979323846 * i) / 1024.0;
    return (int)std::lround(std::sin(a) * 32767.0);
}

int main() {
    FILE* f = fopen("sin_tables.asm", "wb");
    if (!f) return 1;
    std::fprintf(f, "; generated by sin_tables.cpp - do not edit\n");
    std::fprintf(f, "section .data align=16\n");
    std::fprintf(f, "global vkSin\nvkSin:\n");
    for (int i = 0; i < 1024; i++) {
        if (i % 4 == 0) std::fprintf(f, "\n");
        std::fprintf(f, "\tdd %d\n", sv(i));
    }
    std::fprintf(f, "\nglobal sinus\nsinus:\n");
    // NOTE: the engine reads cos as word sinus[256 + (angle&1023)] (byte
    // offset 512 + idx*2), so it can touch indices 256..1279.  Emit two
    // periods (2048 entries) so those reads stay within the table.
    for (int i = 0; i < 2048; i++) {
        if (i % 8 == 0) std::fprintf(f, "\n");
        std::fprintf(f, "\tdw %d\n", sv(i % 1024));
    }
    std::fclose(f);
    return 0;
}
