#!/usr/bin/env python3
"""Build the deterministic single-codec VOODKA runtime payload.

The release uses two independent XZ/LZMA2 streams in one small container. A
single combined stream is a few bytes smaller, but separate streams let the
decoder write the archive and module directly to their final destinations
without a temporary combined buffer or a larger multi-call decoder workspace.
"""

from __future__ import annotations

import argparse
import hashlib
import lzma
import struct
from pathlib import Path


MAGIC = b"VPK1"
VERSION = 1
CODEC_XZ_LZMA2 = 1
HEADER_SIZE = 16 + 2 * 16
PRESET = 9 | lzma.PRESET_EXTREME


def compress(path: Path) -> bytes:
    return lzma.compress(
        path.read_bytes(),
        format=lzma.FORMAT_XZ,
        check=lzma.CHECK_CRC32,
        preset=PRESET,
    )


def write_inc(path: Path, archive: bytes, module: bytes) -> None:
    path.write_text(
        "; generated by compress_assets.py; do not edit\n"
        f"%define VOODKA_ARCHIVE_UNCOMPRESSED_SIZE {len(archive)}\n"
        f"%define VOODKA_MODULE_UNCOMPRESSED_SIZE {len(module)}\n",
        encoding="ascii",
        newline="\n",
    )


def build(archive_path: Path, module_path: Path, output_path: Path, inc_path: Path) -> None:
    archive = archive_path.read_bytes()
    module = module_path.read_bytes()
    archive_stream = compress(archive_path)
    module_stream = compress(module_path)

    archive_offset = HEADER_SIZE
    module_offset = archive_offset + len(archive_stream)
    header = struct.pack(
        "<4sHHII",
        MAGIC,
        VERSION,
        CODEC_XZ_LZMA2,
        2,
        HEADER_SIZE,
    )
    entries = b"".join(
        struct.pack("<IIII", asset_id, len(raw), offset, len(stream))
        for asset_id, raw, offset, stream in (
            (1, archive, archive_offset, archive_stream),
            (2, module, module_offset, module_stream),
        )
    )
    payload = header + entries + archive_stream + module_stream

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(payload)
    inc_path.parent.mkdir(parents=True, exist_ok=True)
    write_inc(inc_path, archive, module)

    print(
        "compressed payload: "
        f"archive {len(archive)} -> {len(archive_stream)}, "
        f"module {len(module)} -> {len(module_stream)}, "
        f"container {len(payload)}"
    )
    print(f"archive sha256: {hashlib.sha256(archive).hexdigest()}")
    print(f"module sha256:  {hashlib.sha256(module).hexdigest()}")


def benchmark(archive_path: Path, module_path: Path) -> None:
    assets = (("vodka.dat", archive_path.read_bytes()), ("amnezja2.mod", module_path.read_bytes()))
    print("codec benchmark; decoder footprint is measured from the Release link")
    for name, raw in assets:
        xz = compress(module_path if name.endswith("mod") else archive_path)
        print(f"{name}: raw={len(raw)} xz-lzma2-extreme={len(xz)}")

        try:
            import brotli

            print(f"{name}: brotli-q11={len(brotli.compress(raw, quality=11, mode=brotli.MODE_GENERIC))}")
        except ImportError:
            print(f"{name}: brotli-q11=unavailable")

        try:
            import zstandard

            compressor = zstandard.ZstdCompressor(level=22, threads=1, write_checksum=True)
            print(f"{name}: zstd-22={len(compressor.compress(raw))}")
        except ImportError:
            print(f"{name}: zstd-22=unavailable")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--archive", type=Path, required=True)
    parser.add_argument("--module", type=Path, required=True)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--inc", type=Path)
    parser.add_argument("--benchmark", action="store_true")
    args = parser.parse_args()

    if args.benchmark:
        benchmark(args.archive, args.module)
        return
    if not args.output or not args.inc:
        parser.error("--output and --inc are required unless --benchmark is used")
    build(args.archive, args.module, args.output, args.inc)


if __name__ == "__main__":
    main()
