  деддддд -ЫЫЫЫЫЫЫЫЫЫЫЫЫЗЗЗЫЫЫЫЫЗЗЗЫЫЗЫЫЫЫЫЗЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫддддддббдддббед
   ЁЫ     З     З                      З                          ЁЁaBcЁЁЁ
   Ё        З      Ы   З шъъъъъшш З        Ы шщ     З     З       юаддбее╢
   Ё    шъъъъъшш  З      ш  шш  ш     чъъщшъъ ъъшш      Ы         З   юае╢
   Ы З  ш  шш  ш    З    ш  шш  шчъщ  ч  щш шчш  ш          З       Ы   ю╢
   Ы    ш  ъъ эшчъщ  чъъщш  шш  шч щ  ч  щш шшш  ш   ээ   эээ    ээээ    Ё
   З    ш  шш  шч щ Ыч  щш  шш  шч ъъъъ  щш шшш  ш  ш  ш  ш  ъэ ш    ш   Ы
   З З  ш  шш  шч щЗ ч  щш  ъъ эш ъъъъъщ щш  шш  ш  шЗ  ш ш   ш шщээъ    З
   Ы    ш  ъъ эшч щ  ч  щшшшшшшшш   Ы  щ щш  шш  ш  ш   ш ш   ш ш    э З Ы
   |    шшшшшшшшч ъъъъ  щ     wlkчъъъъъ  щшшшшшшшш   ъэъ  ш  ъ   ъъъъ    Ы
   Ё  З       Ы  ъъъъъъъ   З      ъъъъъъъ       ЗЗЫЫддддд ш дддддддддд--ЫЁЗЗ
  деддддддЫЫЫЫЗЫЫЗЗЫЫЫЗЗЫЫЫЫЫЫЫЫЫЫЫЫЗЗЫЫЫЫЫЫЫЫЫЗЗЗЗЫЗЫЫЫЫЫЫЫЫЫЫЫ--дддддддед


                       THE VOTESHEET FOR BUDY╔ ISSUE 2
                      ---------------------------------

This is a votesheet to Absence's scene mag called Budy╓. We set deadline for
voting at 1st December. While voting please respect the following rules:

1. Please don't vote for us - Absence and our prods.
2. Please don't vote for yourself and your group.
3. You don't have to fill all charts and all entries by try to fill
   as many charts and entries as possible.
4. You can vote only once per issue.
5. Every voter will be mentioned in voters' list within issue.
6. There is one size of ads: 37x17. Ads that are bigger will be deleted.
   Ads are free. You can write them as many as you want.
7. While writing messages please write To: whom you are writing, From: who
   is the message, and the text. You can write as many messys as you want.
8. Scene news you wanna share with us should be truth. We don't accept
   any rumours.
9. To see where to send your votes, see the end of the sheet.



                          зд д д д ЗЗЗ  ЗЗЗ д д д  д©
                          Ё      TOP 10 DEMOS       Ё
 З З З З З З д д д д дддддаддд дд д З З З З д дд дддаддддд д д д д З З З З З З

           1.
           2.
           3.
           4.
           5.
           6.
           7.
           8.
           9.
           X.
                          зд д д д ЗЗЗ  ЗЗЗ д д д  д©
                          Ё      TOP 10 INTROS      Ё
 З З З З З З д д д д дддддаддд дд д З З З З д дд дддаддддд д д д д З З З З З З

           1.
           2.
           3.
           4.
           5.
           6.
           7.
           8.
           9.
           X.
                          зд д д д ЗЗЗ  ЗЗЗ д д д  д©
                          Ё      TOP 10 GROUPS      Ё
 З З З З З З д д д д дддддаддд дд д З З З З д дд дддаддддд д д д д З З З З З З

           1.
           2.
           3.
           4.
           5.
           6.
           7.
           8.
           9.
           X.
                          зд д д д ЗЗЗ  ЗЗЗ д д д  д©
                          Ё      TOP 10 CODERS      Ё
 З З З З З З д д д д дддддаддд дд д З З З З д дд дддаддддд д д д д З З З З З З

           1.
           2.
           3.
           4.
           5.
           6.
           7.
           8.
           9.
           X.
                          зд д д д ЗЗЗ  ЗЗЗ д д д  д©
                          Ё    TOP 10 MUSICIANS     Ё
 З З З З З З д д д д дддддаддд дд д З З З З д дд дддаддддд д д д д З З З З З З

           1.
           2.
           3.
           4.
           5.
           6.
           7.
           8.
           9.
           X.
                          зд д д д ЗЗЗ  ЗЗЗ д д д  д©
                          Ё   TOP 10 GRAPHICIANS    Ё
 З З З З З З д д д д дддддаддд дд д З З З З д дд дддаддддд д д д д З З З З З З

           1.
           2.
           3.
           4.
           5.
           6.
           7.
           8.
           9.
           X.
                          зд д д д ЗЗЗ  ЗЗЗ д д д  д©
                          Ё     TOP 10 SWAPPERS     Ё
 З З З З З З д д д д дддддаддд дд д З З З З д дд дддаддддд д д д д З З З З З З

           1.
           2.
           3.
           4.
           5.
           6.
           7.
           8.
           9.
           X.
                          зд д д д ЗЗЗ  ЗЗЗ д д д  д©
                          Ё     TOP 10 DISKMAGS     Ё
 З З З З З З д д д д дддддаддд дд д З З З З д дд дддаддддд д д д д З З З З З З

           1.
           2.
           3.
           4.
           5.
           6.
           7.
           8.
           9.
           X.
                          зд д д д ЗЗЗ  ЗЗЗ д д д  д©
                          Ё TOP 10 ARTICLE WRITERS  Ё
 З З З З З З д д д д дддддаддд дд д З З З З д дд дддаддддд д д д д З З З З З З

           1.
           2.
           3.
           4.
           5.
           6.
           7.
           8.
           9.
           X.
                          зд д д д ЗЗЗ  ЗЗЗ д д д  д©
                          Ё   TOP 5 POLISH DEMOS    Ё
 З З З З З З д д д д дддддаддд дд д З З З З д дд дддаддддд д д д д З З З З З З

           1.
           2.
           3.
           4.
           5.
                          зд д д д ЗЗЗ  ЗЗЗ д д д  д©
                          Ё   TOP 5 POLISH INTROS   Ё
 З З З З З З д д д д дддддаддд дд д З З З З д дд дддаддддд д д д д З З З З З З

           1.
           2.
           3.
           4.
           5.
                          зд д д д ЗЗЗ  ЗЗЗ д д д  д©
                          Ё   TOP 5 POLISH GROUPS   Ё
 З З З З З З д д д д дддддаддд дд д З З З З д дд дддаддддд д д д д З З З З З З

           1.
           2.
           3.
           4.
           5.
                          зд д д д ЗЗЗ  ЗЗЗ д д д  д©
                          Ё   TOP 5 POLISH CODERS   Ё
 З З З З З З д д д д дддддаддд дд д З З З З д дд дддаддддд д д д д З З З З З З

           1.
           2.
           3.
           4.
           5.
                          зд д д д ЗЗЗ  ЗЗЗ д д д  д©
                          Ё TOP 5 POLISH MUSICIANS  Ё
 З З З З З З д д д д дддддаддд дд д З З З З д дд дддаддддд д д д д З З З З З З

           1.
           2.
           3.
           4.
           5.
                          зд д д д ЗЗЗ  ЗЗЗ д д д  д©
                          ЁTOP 5 POLISH GRAPHICIANS Ё
 З З З З З З д д д д дддддаддд дд д З З З З д дд дддаддддд д д д д З З З З З З

           1.
           2.
           3.
           4.
           5.
                       зд д д д ЗЗЗ ЗЗЗ ЗЗЗ ЗЗд д д  д©
                       Ё TOP 5 POLISH ARTICLE WRITERS Ё
 З З З З З З д д д д ддаддд дд д З З З З З З Зд дд дддаддддд д д д д З З З З З З

           1.
           2.
           3.
           4.
           5.
                          зд д д д ЗЗЗ  ЗЗЗ д д д  д©
                          Ё     TECHNICAL STUFF     Ё
 З З З З З З д д д д дддддаддд дд д З З З З д дд дддаддддд д д д д З З З З З З


           Some infos about you:

             Handle:
              Group:
           Function:
            Country: 
               Date:

           Some opinions about our mag (critisism is welcome!):





                      зд д д д З З З З З З З З д д д  д©
                      Ё WANNA SHARE SOME NEWS WITH US? Ё
 З З З З д д д д   дддадд дд дд д З З З З д дд дд дддддаддддд д д д З З З З З З




                      зд д д д З З З З З З З З д д д  д©
                      Ё HERE PLEASE PUT YOUR 37x17 ADS Ё
 З З З З д д д дд д ддадд дд дд д З З З З д дд дд дддддаддддд д д д д З З З З З




                      зд д д д З З З З З З З З д д д  д©
                      Ё HERE PLEASE PUT YOUR MESSAGES  Ё
 З З З З д д д дд д ддадд дд дд д З З З З д дд дд дддддаддддд д д д д З З З З З





                          зд д д д ЗЗЗ  ЗЗЗ д д д  д©
                          Ё  WHERE SEND YOUR VOTES  Ё
 З З З З З З д д д д дддддаддд дд д З З З З д дд дддаддддд д д д д З З З З З З


         Filled votes please send to one of the following addresses:

         snail-mail:                              (main editor)

         Cortez / Absence                         Brach / Absence
         Michal Krasnodebski                      Zbyszek Cholewa
         ul. Zakatek 5/19                         ul. Nowa 5/14
         30-076 Krakow                            32-332 Bukowno
         Poland                                   Poland


        internet e-mail:

        Astra / Absence
        s146630@ire.pw.edu.pl (preferred!)
        mszklan@ire.pw.edu.pl

        phone-mail: 	+048 (0-35) 42-20-11 (warlock or tomek)


